sink:
  # -- Name of the connector Kafka consumer group
  name: radar-timescale-sink
  # -- create table if it does not exist
  autoCreate: true
  # -- How to insert new values into the database
  insertMode: upsert
  # -- Whether to merge the key fields into the inserted values.
  mergeKey: true
  primaryKeys:
    # -- where to read the primary keys from when creating the table
    mode: record_value
    # -- fields to include as primary keys when creating the table
    fields:
      - TIME
      - USERID
      - PROJECTID
  # -- Comma-separated list of topics the connector will read from and ingest into the database
  topics: PUSH_GARMIN_HEART_RATE_SAMPLE_TIMESTAMP_LONG_WINDOWED_1H_TABLE,PUSH_GARMIN_PULSE_OX_TIMESTAMP_LONG_WINDOWED_1H_TABLE,PUSH_GARMIN_BODY_BATTERY_TIMESTAMP_LONG_WINDOWED_1H_TABLE,QUESTIONNAIRE_CAT_SCORE_STREAM,QUESTIONNAIRE_PULSE_OX_SCORE_STREAM,QUESTIONNAIRE_VAS_SCORE_STREAM,QUESTIONNAIRE_LIPF_SCORE_STREAM,QUESTIONNAIRE_RALPMH_COVID_SYMPTOMS_SCORE_STREAM,QUESTIONNAIRE_ERS_SCORE_STREAM,PUSH_GARMIN_RESPIRATION_TIMESTAMP_LONG_WINDOWED_1H_TABLE,PUSH_GARMIN_STRESS_LEVEL_TIMESTAMP_LONG_WINDOWED_1H_TABLE,REST_API_INFERENCE_LSTM_COPD,QUESTIONNAIRE_EXACERBATION_DIARY_SCORE_STREAM,QUESTIONNAIRE_ERS_SCORE_UPDATED_STREAM
  # -- How to format a table name based on the inserted topic
  tableNameFormat: "${topic}"
