apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc-schema-registry-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cc-schema-registry-proxy.name" . }}
    helm.sh/chart: {{ include "cc-schema-registry-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.service.externalName }}
  selector:
    app.kubernetes.io/name: {{ include "cc-schema-registry-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
