{{- if .Values.cc.enabled }}
{{- $jaasConfig := print `org.apache.kafka.common.security.plain.PlainLoginModule required username="` .Values.cc.apiKey `" password="` .Values.cc.apiSecret `";` -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radar-s3-connector.fullname" . }}
  labels:
    app: {{ template "radar-s3-connector.name" . }}
    chart: {{ template "radar-s3-connector.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  schemaRegistryCredential: {{ print .Values.cc.schemaRegistryApiKey ":" .Values.cc.schemaRegistryApiSecret | b64enc | quote }}
  kafkaSaslJaasConfig: {{ $jaasConfig | b64enc | quote }}
  awsAccessKey: {{ .Values.bucketAccessKey | b64enc | quote }}
  awsSecretKey: {{ .Values.bucketSecretKey | b64enc | quote }}
{{- end -}}
