ingress:
  admin:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: radar-k3s-test.thehyve.net
        paths:
          - path: "/admin/hydra/?(.*)"
            pathType: ImplementationSpecific
    tls:
      - secretName: radar-base-tls
        hosts:
          - localhost
  public:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: localhost
        paths:
          - path: "/hydra/?(.*)"
            pathType: ImplementationSpecific
    tls:
      - secretName: hydra-public-tls
        hosts:
          - localhost
hydra:
  automigration:
    enabled: true
  config:
    urls:
      self:
        issuer: https://localhost/hydra/
      login: https://localhost/login
      consent: https://localhost/hydra-ui/consent

    log:
      level: debug
      format: text
      leak_sensitive_values: false

    strategies:
      access_token: jwt

    oauth2:
      allowed_top_level_claims: scope,roles,authorities,sources,user_name
      mirror_top_level_claims: false
    
    serve:
      public:
        base_url: https://localhost/hydra/
        cors:
          enabled: true
          allowed_origins:
            - "*"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - Content-Type
            - Accept
          exposed_headers:
            - Content-Type
            - Set-Cookie
            - Accept
          allow_credentials: true
      admin:
        base_url: https://localhost/admin/hydra/
        cors:
          enabled: true
