{{- if .Values.postgres.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "management-portal.fullname" . }}-root-cert
  labels:
    app: {{ template "management-portal.name" . }}
    chart: {{ template "management-portal.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  root.crt: {{ .Files.Get "files/root.crt" | b64enc | quote }}
{{ end }}
