# See:
# - https://github.com/k3d-io/k3d/issues/19#issuecomment-1967513596
# - https://github.com/ligfx/k3d-registry-dockerd
apiVersion: k3d.io/v1alpha5
kind: Simple
volumes:
  - volume: $HOME/k3d-containerd:/var/lib/rancher/k3s/agent/containerd/
    nodeFilters:
      - server:0
registries:
  create:
    image: ligfx/k3d-registry-dockerd:v0.8
    proxy:
      remoteURL: "*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
options:
  k3s:
    extraArgs:
      - arg: --disable=helm-controller
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  runtime:
    # Raise host container (k3d node) ulimit for open files so Elasticsearch passes bootstrap checks
    # Elasticsearch requires at least 65535; we set higher to allow headroom.
    ulimits:
      - name: nofile
        soft: 1048576
        hard: 1048576
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:443:443
    nodeFilters:
      - loadbalancer
  # This port mapping is required for Nifi to work correctly when TLS is disabled.
  # The service frontend should derive the port from the ProxyPort header returned by Nginx, but does not.
  - port: 0.0.0.0:8080:80
    nodeFilters:
      - loadbalancer
