{{- range $username, $fields := .Values.s3Config.identities }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-credentials-{{ $username }}
  labels: {{ include "common.labels.standard" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  accessKey: {{ $fields.credentials.accessKey | b64enc | quote }}
  secretKey: {{ $fields.credentials.secretKey | b64enc | quote }}
{{- end }}
