apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  sink-iceberg.properties: |
    name=radar-iceberg-sink-connector
    connector.class=org.apache.iceberg.connect.IcebergSinkConnector
    tasks.max={{ .Values.maxTasks | int }}
    format.class=io.confluent.connect.s3.format.avro.AvroFormat
    flush.size={{ .Values.flushSize | int }}
    topics={{ .Values.topics }}
    connect.meta.data=false
    rotate.schedule.interval.ms={{ .Values.rotateInterval | int }}
    timezone=UTC
    iceberg.control.group-id-prefix=cg-control
    iceberg.coordinator.transactional.id.prefix=NEW_2_
    iceberg.control.group-id=lalalalalalal
    iceberg.catalog.uri={{ .Values.iceberg.catalog.uri }}
    iceberg.catalog.type={{ .Values.iceberg.catalog.type }}
    iceberg.catalog.io-impl={{ .Values.iceberg.catalog.ioImpl }}
    iceberg.catalog.s3.endpoint={{ .Values.iceberg.s3.endpoint }}
    iceberg.catalog.s3.path-style-access={{ .Values.iceberg.s3.pathStyleAccess }}
    #iceberg.tables.dynamic-enabled=true
    iceberg.tables={{ .Values.iceberg.tables.tables }}
    iceberg.control.topic={{ .Values.iceberg.control.topic }}
    iceberg.tables.auto-create-enabled={{ .Values.iceberg.tables.autoCreateEnabled }}
    iceberg.tables.dynamic-schema-evolution-enabled={{ .Values.iceberg.tables.automaticSchemaEvolutionEnabled }}
    # Kafka producer configuration for transaction coordinator discovery
    producer.retry.backoff.ms=1000
    producer.max.block.ms=30000
    producer.metadata.max.age.ms=30000

    {{/*-1 means use default configured by the kafka broker*/}}
    config.storage.replication.factor=-1
    offset.storage.replication.factor=-1
    status.storage.replication.factor=-1
    topic.creation.default.replication.factor=-1

    # --
    avro.codec=deflate
    errors.tolerance=all
    errors.log.enable=true
    errors.retry.delay.max.ms=60000
    errors.retry.timeout=300000
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -sf localhost:8083/connectors/radar-iceberg-sink-connector/status | grep -o '\"state\":\"[^\"]*\"')
    if echo "$STATUS" | tr '\\n' ',' | grep -q FAILED; then
      exit 1
    elif [ $(echo "$STATUS" | grep RUNNING | wc -l) -le 1 ]; then
      exit 1
    fi
  add-topics-to-config.sh: |
    #!/usr/bin/env sh
    SOURCE=$1
    TARGET=$2
    set -e
    TOPICS="$(curl -sf {{ .Values.catalogServer.url }}/source-types | jq -r '[to_entries | .[] | select(.key | test("^.*-source-types$")) | .value[].data[].topic] | sort | unique | join(",")')"
    if [ "$TOPICS" == "" ]; then
      echo "No topics found!"
      exit 1
    fi
    sed "s/^topics=.\+\$/\\0,$TOPICS/" "$SOURCE" | sed "s/^topics=\$/\\0$TOPICS/" > "$TARGET"
    echo "Configured the following topics"
    grep "topics=" "$TARGET"
