apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  sink-iceberg.properties: |
    name={{ .Values.connectorName }}
    {{- if .Values.schemaRegistry }}
    key.converter.schema.registry.url={{ .Values.schemaRegistry.url }}
    value.converter.schema.registry.url={{ .Values.schemaRegistry.url }}
    {{- end }}
    tasks.max={{ .Values.maxTasks }}
    topics={{ .Values.topics }}
    iceberg.control.group-id={{ include "common.names.fullname" . }}
    {{- with .Values.extraConnectConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  healthcheck.sh: |
    #!/bin/sh
    STATUS=$(curl -sf localhost:8083/connectors/{{ .Values.connectorName }}/status | grep -o '\"state\":\"[^\"]*\"')
    if echo "$STATUS" | tr '\\n' ',' | grep -q FAILED; then
      exit 1
    elif [ $(echo "$STATUS" | grep RUNNING | wc -l) -le 1 ]; then
      exit 1
    fi
  add-topics-to-config.sh: |
    #!/usr/bin/env sh
    SOURCE=$1
    TARGET=$2
    set -e
    TOPICS="$(curl -sf {{ .Values.catalogServer.url }}/source-types | jq -r '[to_entries | .[] | select(.key | test("^.*-source-types$")) | .value[].data[].topic] | sort | unique | join(",")')"
    if [ "$TOPICS" == "" ]; then
      echo "No topics found!"
      exit 1
    fi
    sed "s/^topics=.\+\$/\\0,$TOPICS/" "$SOURCE" | sed "s/^topics=\$/\\0$TOPICS/" > "$TARGET"
    echo "Configured the following topics"
    grep "topics=" "$TARGET"
