bases:
- ../environments.yaml

---

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: elastic
  url: https://helm.elastic.co
- name: jetstack
  url: https://charts.jetstack.io
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts


helmDefaults:
  atomic: true
  # force: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: mongodb
    namespace: graylog
    chart: stable/mongodb-replicaset
    version: 3.11.5
    installed: {{ .Values.mongodb._install }}
    values:
      - "../etc/mongodb/values.yaml"
      - {{ .Values.mongodb | toYaml | indent 8 | trim }}

  - name: elasticsearch
    namespace: graylog
    chart: elastic/elasticsearch
    version: 7.6.0
    installed: {{ .Values.elasticsearch._install }}
    set:
      - name: imageTag
        value: "6.8.6"
      - name: resources.requests.memory
        value: "1.5Gi"

  - name: graylog
    namespace: graylog
    chart: stable/graylog
    version: 1.5.6
    installed: {{ .Values.graylog._install }}
    values:
      - "../etc/graylog/values.yaml"
      - {{ .Values.graylog | toYaml | indent 8 | trim }}
    set:
      - name: graylog.rootEmail
        value: {{ .Values.maintainer_email }}
      - name: graylog.ingress.hosts
        values: [graylog.{{ .Values.server_name }}]
      - name: graylog.ingress.tls[0].secretName
        value: radar-base-tls
      - name: graylog.ingress.tls[0].hosts
        values: ["graylog.{{ .Values.server_name }}"]

  - name: fluentd
    namespace: graylog
    chart: ../charts/fluentd
    installed: {{ .Values.fluentd._install }}
    values:
      - {{ .Values.fluentd | toYaml | indent 8 | trim }}

  - name: cert-manager
    namespace: cert-manager
    wait: true
    installed: {{ .Values.cert_manager._install }}
    chart: ../charts/cert-manager
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["--context", "{{ .Values.kubeContext }}", "apply", "-f", "../charts/cert-manager/files/crds.yaml"]
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: maintainer_email
        value: {{ .Values.maintainer_email }}

  - name: kube-prometheus-stack
    chart: ../charts/kube-prometheus-stack
    wait: true
    namespace: monitoring
    installed: {{ .Values.kube_prometheus_stack._install }}
    values:
      - {{ .Values.kube_prometheus_stack | toYaml | indent 8 | trim }}
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: kube-prometheus-stack.prometheus.ingress.hosts
        values: ["prometheus.{{ .Values.server_name }}"]
      - name: kube-prometheus-stack.prometheus.ingress.tls[0].secretName
        value: radar-base-tls-prometheus
      - name: kube-prometheus-stack.prometheus.ingress.tls[0].hosts
        values: ["prometheus.{{ .Values.server_name }}"]

      - name: kube-prometheus-stack.alertmanager.ingress.hosts
        values: ["alertmanager.{{ .Values.server_name }}"]
      - name: kube-prometheus-stack.alertmanager.ingress.tls[0].secretName
        value: radar-base-tls-alertmanager
      - name: kube-prometheus-stack.alertmanager.ingress.tls[0].hosts
        values: ["alertmanager.{{ .Values.server_name }}"]

      - name: kube-prometheus-stack.grafana.ingress.hosts
        values: ["grafana.{{ .Values.server_name }}"]
      - name: kube-prometheus-stack.grafana.ingress.tls[0].secretName
        value: radar-base-tls-grafana
      - name: kube-prometheus-stack.grafana.ingress.tls[0].hosts
        values: ["grafana.{{ .Values.server_name }}"]

  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.40.2
    force: false
    installed: {{ .Values.nginx_ingress._install }}
    values:
      - "../etc/nginx-ingress/values.yaml"
      - {{ .Values.nginx_ingress | toYaml | indent 8 | trim }}

  - name: kafka-manager
    chart: ../charts/kafka-manager
    wait: false
    installed: {{ .Values.kafka_manager._install }}
    values:
      - {{ .Values.kafka_manager | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values:
          - {{ .Values.server_name }}
      - name: ingress.tls[0].secretName
        value: radar-base-tls
      - name: ingress.tls[0].hosts
        values:
          - {{ .Values.server_name }}
