bases:
- ../environments.yaml

---

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: elastic
  url: https://helm.elastic.co

helmDefaults:
  atomic: true
  # force: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: mongodb
    namespace: graylog
    chart: stable/mongodb-replicaset
    version: 3.11.5
    installed: {{ .Values.mongodb._install }}
    values:
      - "../charts/mongodb/values.yaml"
      - {{ .Values.mongodb | toYaml | indent 8 | trim }}

  - name: elasticsearch
    namespace: graylog
    chart: elastic/elasticsearch
    version: 7.6.0
    installed: {{ .Values.elasticsearch._install }}
    set:
      - name: imageTag
        value: "6.8.6"

  - name: graylog
    namespace: graylog
    chart: stable/graylog
    version: 1.5.6
    installed: {{ .Values.graylog._install }}
    values:
      - "../charts/graylog/values.yaml"
      - {{ .Values.graylog | toYaml | indent 8 | trim }}
    set:
      - name: graylog.rootEmail
        value: {{ .Values.maintainer_email }}
      - name: graylog.ingress.hosts
        values: [graylog.{{ .Values.server_name }}]
      - name: graylog.ingress.tls[0].secretName
        value: radar-base-tls
      - name: graylog.ingress.tls[0].hosts
        values: ["graylog.{{ .Values.server_name }}"]

  - name: fluentd
    namespace: graylog
    chart: ../charts/fluentd
    installed: {{ .Values.fluentd._install }}
    values:
      - "../charts/fluentd/values.yaml"
      - {{ .Values.fluentd | toYaml | indent 8 | trim }}

  - name: cert-manager
    namespace: cert-manager
    wait: true
    installed: {{ .Values.cert_manager._install }}
    chart: ../charts/cert-manager
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: maintainer_email
        value: {{ .Values.maintainer_email }}

  - name: prometheus-operator
    chart: ../charts/prometheus-operator
    wait: true
    namespace: monitoring
    installed: {{ .Values.prometheus_operator._install }}
    values:
      - "../charts/prometheus-operator/values.yaml"
      - {{ .Values.prometheus_operator | toYaml | indent 8 | trim }}
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: prometheus-operator.prometheus.ingress.hosts
        values: ["prometheus.{{ .Values.server_name }}"]
      - name: prometheus-operator.prometheus.ingress.tls[0].secretName
        value: radar-base-tls-prometheus
      - name: prometheus-operator.prometheus.ingress.tls[0].hosts
        values: ["prometheus.{{ .Values.server_name }}"]

      - name: prometheus-operator.alertmanager.ingress.hosts
        values: ["alertmanager.{{ .Values.server_name }}"]
      - name: prometheus-operator.alertmanager.ingress.tls[0].secretName
        value: radar-base-tls-alertmanager
      - name: prometheus-operator.alertmanager.ingress.tls[0].hosts
        values: ["alertmanager.{{ .Values.server_name }}"]

      - name: prometheus-operator.grafana.ingress.hosts
        values: ["grafana.{{ .Values.server_name }}"]
      - name: prometheus-operator.grafana.ingress.tls[0].secretName
        value: radar-base-tls-grafana
      - name: prometheus-operator.grafana.ingress.tls[0].hosts
        values: ["grafana.{{ .Values.server_name }}"]

  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.40.2
    force: false
    installed: {{ .Values.nginx_ingress._install }}
    values:
      - "../charts/nginx-ingress/values.yaml"
      - {{ .Values.nginx_ingress | toYaml | indent 8 | trim }}

  - name: kafka-manager
    chart: ../charts/kafka-manager
    wait: false
    installed: {{ .Values.kafka_manager._install }}
    values:
      - {{ .Values.kafka_manager | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values:
          - {{ .Values.server_name }}
      - name: ingress.tls[0].secretName
        value: radar-base-tls
      - name: ingress.tls[0].hosts
        values:
          - {{ .Values.server_name }}
