bases:
- ../environments.yaml

---

releases:
  - name: kratos
    chart: ory/kratos
    version: {{ .Values.kratos._chart_version }}
    installed: {{ .Values.kratos._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos._extra_timeout }}
    values:
      - "../etc/kratos/values.yaml"
      - {{ .Values.kratos | toYaml | indent 8 | trim }}
    set:
      - name: serverName
        value: {{ .Values.server_name }}
      {{- $values := .Values.kratos }}
      {{- $hasPublicIngress := and (hasKey $values "public") (hasKey $values.public "ingress") }}
      {{- $useTLSPublic := or (not $hasPublicIngress) (not (kindIs "invalid" $values.public.ingress.tls)) }}
      {{- if $useTLSPublic }}
      - name: ingress.public.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.admin.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      {{- end }}
      {{- $hasAdminIngress := and (hasKey $values "admin") (hasKey $values.admin "ingress") }}
      {{- $useTLSAdmin := or (not $hasAdminIngress) (not (kindIs "invalid" $values.admin.ingress.tls)) }}
      {{- if $useTLSAdmin }}
      - name: ingress.admin.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.public.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      {{- end }}

  - name: kratos-selfservice-ui-node
    chart: ory/kratos-selfservice-ui-node
    version: {{ .Values.kratos_ui._chart_version }}
    installed: {{ .Values.kratos_ui._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos_ui._extra_timeout }}
    values:
      - "../etc/kratos_ui/values.yaml"
      - {{ .Values.kratos_ui | toYaml | indent 8 | trim }}
