bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: cp-zookeeper
    chart: ../cp-helm-charts/charts/cp-zookeeper
    wait: true
    installed: {{ .Values.cp_zookeeper._install }}
    values:
      - {{ .Values.cp_zookeeper | toYaml | indent 8 | trim }}
  - name: cp-kafka
    chart: ../cp-helm-charts/charts/cp-kafka
    wait: true
    installed: {{ .Values.cp_kafka._install }}
    values:
      - "../charts/cp-kafka/values.yaml"
      - {{ .Values.cp_kafka | toYaml | indent 8 | trim }}
    set:
      - name: brokers
        value: {{ .Values.kafka_num_brokers }}
  - name: cp-schema-registry
    chart: ../cp-helm-charts/charts/cp-schema-registry
    wait: true
    installed: {{ .Values.cp_schema_registry._install }}
    values:
      - "../charts/cp-schema-registry/values.yaml"
      - {{ .Values.cp_schema_registry | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts[0].host
        value: "{{ .Values.server_name }}"
      - name: ingress.hosts[0].paths
        values: ["/schema/?(.*)"]
      - name: ingress.tls[0].secretName
        value: radar-base-tls
      - name: ingress.tls[0].hosts
        values: ["{{ .Values.server_name }}"]

  - name: catalog-server
    chart: ../charts/catalog-server
    wait: true
    installed: {{ .Values.catalog_server._install }}
    values:
      - "../charts/catalog-server/values.yaml"
      - {{ .Values.catalog_server | toYaml | indent 8 | trim }}
      - {{ .Values.confluent_cloud | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: cc.enabled
        value: {{ .Values.confluent_cloud.enabled }}
      {{- if .Values.confluent_cloud.enabled }}
      - name: schema_registry
        value: {{ .Values.confluent_cloud.cc.schemaRegistryUrl }}
      {{ end }}
