bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts
  - name: cp-radar
    url: https://radar-base.github.io/cp-helm-charts

releases:
  - name: cert-manager-letsencrypt
    namespace: cert-manager
    wait: true
    installed: {{ .Values.cert_manager_letsencrypt._install }}
    chart: radar/cert-manager-letsencrypt
    version: {{ .Values.cert_manager_letsencrypt._chart_version }}
    set:
      - name: maintainerEmail
        value: {{ .Values.maintainer_email }}

  - name: cp-zookeeper
    chart: cp-radar/cp-zookeeper
    version: {{ .Values.cp_zookeeper._chart_version }}
    wait: true
    installed: {{ .Values.cp_zookeeper._install }}
    values:
      - "../etc/cp-zookeeper/values.yaml"
      - {{ .Values.cp_zookeeper | toYaml | indent 8 | trim }}

  - name: cp-kafka
    chart: cp-radar/cp-kafka
    version: {{ .Values.cp_kafka._chart_version }}
    wait: true
    installed: {{ .Values.cp_kafka._install }}
    values:
      - "../etc/cp-kafka/values.yaml"
      - {{ .Values.cp_kafka | toYaml | indent 8 | trim }}
    set:
      - name: brokers
        value: {{ .Values.kafka_num_brokers }}

  - name: cp-schema-registry
    chart: cp-radar/cp-schema-registry
    version: {{ .Values.cp_schema_registry._chart_version }}
    wait: true
    installed: {{ .Values.cp_schema_registry._install }}
    values:
      - "../etc/cp-schema-registry/values.yaml"
      - {{ .Values.cp_schema_registry | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts[0].host
        value: "{{ .Values.server_name }}"
      - name: ingress.hosts[0].paths
        values: ["/schema/?(.*)"]
      - name: ingress.tls[0].secretName
        value: radar-base-tls
      - name: ingress.tls[0].hosts
        values: ["{{ .Values.server_name }}"]

  - name: catalog-server
    chart: radar/catalog-server
    version: {{ .Values.catalog_server._chart_version }}
    wait: true
    installed: {{ .Values.catalog_server._install }}
    values:
      - {{ .Values.catalog_server | toYaml | indent 8 | trim }}
      - {{ .Values.confluent_cloud | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: cc.enabled
        value: {{ .Values.confluent_cloud.enabled }}
      {{- if .Values.confluent_cloud.enabled }}
      - name: schema_registry
        value: {{ .Values.confluent_cloud.cc.schemaRegistryUrl }}
      {{ end }}

  - name: radar-home
    chart: radar/radar-home
    version: {{ .Values.radar_home._chart_version }}
    installed: {{ .Values.radar_home._install }}
    values:
      - {{ .Values.radar_home | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [ {{ .Values.server_name }} ]
      {{- if or (not (hasKey .Values.radar_home "s3")) (not (hasKey .Values.radar_home.s3 "enabled")) }}
      - name: s3.enabled
        value: {{ .Values.minio._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "s3")) (not (hasKey .Values.radar_home.s3 "url")) }}
      - name: s3.url
        value: https://s3.{{ .Values.server_name }}/login
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "dashboard")) (not (hasKey .Values.radar_home.dashboard "enabled")) }}
      - name: dashboard.enabled
        value: {{ .Values.radar_grafana._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "dashboard")) (not (hasKey .Values.radar_home.dashboard "url")) }}
      - name: dashboard.url
        value: https://dashboard.{{ .Values.server_name }}/
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "uploadPortal")) (not (hasKey .Values.radar_home.uploadPortal "enabled")) }}
      - name: uploadPortal.enabled
        value: {{ .Values.radar_upload_connect_frontend._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "restAuthorizer")) (not (hasKey .Values.radar_home.restAuthorizer "enabled")) }}
      - name: restAuthorizer.enabled
        value: {{ .Values.radar_rest_sources_authorizer._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "monitoring")) (not (hasKey .Values.radar_home.monitoring "enabled")) }}
      - name: monitoring.enabled
        value: {{ .Values.kube_prometheus_stack._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "monitoring")) (not (hasKey .Values.radar_home.monitoring "url")) }}
      - name: monitoring.url
        value: https://grafana.{{ .Values.server_name }}/login
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "logging")) (not (hasKey .Values.radar_home.logging "enabled")) }}
      - name: logging.enabled
        value: {{ .Values.graylog._install }}
      {{- end }}
      {{- if or (not (hasKey .Values.radar_home "logging")) (not (hasKey .Values.radar_home.logging "url")) }}
      - name: logging.url
        value: https://graylog.{{ .Values.server_name }}/
      {{- end }}
