bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: postgresql
    chart: radar/postgresql
    version: {{ .Values.postgresql._chart_version }}
    installed: {{ .Values.postgresql._install }}
    timeout: {{ add .Values.base_timeout .Values.postgresql._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/postgresql/values.yaml"
      - {{ .Values.postgresql | toYaml | indent 8 | trim }}

  - name: management-portal
    chart: radar/management-portal
    version: {{ .Values.management_portal._chart_version }}
    installed: {{ .Values.management_portal._install }}
    timeout: {{ add .Values.base_timeout .Values.management_portal._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.management_portal | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: ingress_rate_limited.hosts
        values: [{{ .Values.server_name }}]
      - name: server_name
        value: {{ .Values.server_name }}
      - name: oauth_clients.radar_redcap_integrator.enable
        value: {{ .Values.radar_integration._install }}
      - name: oauth_clients.radar_upload_connect.enable
        value: {{ .Values.radar_upload_source_connector._install }}
      - name: oauth_clients.radar_upload_frontend.enable
        value: {{ .Values.radar_upload_connect_frontend._install }}
      - name: oauth_clients.radar_upload_backend.enable
        value: {{ .Values.radar_upload_connect_backend._install }}
      - name: oauth_clients.radar_rest_sources_authorizer.enable
        value: {{ .Values.radar_rest_sources_authorizer._install }}
      - name: oauth_clients.radar_rest_sources_auth_backend.enable
        value: {{ .Values.radar_rest_sources_backend._install }}
      - name: oauth_clients.radar_fitbit_connector.enable
        value: {{ .Values.radar_fitbit_connector._install }}
      - name: oauth_clients.radar_appconfig.enable
        value: {{ .Values.app_config._install }}
      - name: oauth_clients.appconfig_frontend.enable
        value: {{ .Values.app_config_frontend._install }}
      - name: oauth_clients.grafana_dashboard.enable
        value: {{ .Values.radar_grafana._install }}
      - name: oauth_clients.radar_push_endpoint.enable
        value: {{ .Values.radar_push_endpoint._install }}
      - name: oauth_clients.grafana_dashboard.redirect_uri
        values:
          - "https://dashboard.{{ .Values.server_name }}/login/generic_oauth"

  - name: app-config
    chart: radar/app-config
    version: {{ .Values.app_config._chart_version }}
    installed: {{ .Values.app_config._install }}
    timeout: {{ add .Values.base_timeout .Values.app_config._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.app_config | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: clientSecret
        value: {{ .Values.management_portal.oauth_clients.radar_appconfig.client_secret }}

  - name: app-config-frontend
    chart: radar/app-config-frontend
    version: {{ .Values.app_config_frontend._chart_version }}
    installed: {{ .Values.app_config_frontend._install }}
    timeout: {{ add .Values.base_timeout .Values.app_config_frontend._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.app_config_frontend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: authUrl
        value: https://{{ .Values.server_name }}/managementportal/oauth
      - name: authCallbackUrl
        value: https://{{ .Values.server_name }}/appconfig/login

  - name: kratos
    chart: radar/kratos
    version: {{ .Values.kratos._chart_version }}
    installed: {{ .Values.kratos._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/kratos/values.yaml"
      - {{ .Values.kratos | toYaml | indent 8 | trim }}
    set:
      - name: serverName
        value: {{ .Values.server_name }}
      - name: kratos.config.dsn
        value: postgres://{{ .Values.management_portal.postgres.user }}:{{ .Values.management_portal.postgres.password }}@{{ .Values.management_portal.postgres.host }}:{{ .Values.management_portal.postgres.port }}/{{ .Values | get "kratos.jdbc.database" "kratos" }}
      - name: kratos.config.courier.smtp.connection_uri
        #  Note: encoding of "/" in password is necessary for the smtp connection_uri because kratos is not able to handle this.
        value: smtp://{{ .Values.management_portal.smtp.username }}:{{ replace "/" "%2F" .Values.management_portal.smtp.password }}@{{ .Values.management_portal.smtp.host }}:{{ .Values | get "management_portal.smtp.port" 587 }}
      - name: kratos.config.serve.public.base_url
        value: https://{{ .Values.server_name }}/kratos/
      - name: kratos.config.serve.admin.base_url
        value: https://{{ .Values.server_name }}/admin/kratos/
      - name: kratos.config.serve.public.cors.allowed_origins
        values:
        - https://{{ .Values.server_name }}/kratos-ui/
      - name: kratos.config.selfservice.default_browser_return_url
        value: https://{{ .Values.server_name }}/managementportal
      - name: kratos.config.selfservice.allowed_return_urls
        values:
          - https://{{ .Values.server_name }}/
          # FIXME: http://localhost/ is not a valid return URL for production
          - http://{{ .Values.server_name }}/
      - name: kratos.config.selfservice.flows.error.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/error
      - name: kratos.config.selfservice.flows.settings.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/settings
      - name: kratos.config.selfservice.flows.recovery.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/recovery
      - name: kratos.config.selfservice.flows.registration.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/registration
      - name: kratos.config.selfservice.flows.login.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/login
      - name: kratos.config.selfservice.flows.logout.after.default_browser_return_url
        value: https://{{ .Values.server_name }}/kratos-ui/login
      - name: kratos.config.selfservice.flows.verification.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/verification
      - name: kratos.config.selfservice.flows.verification.after.default_browser_return_url
        value: https://{{ .Values.server_name }}/kratos-ui
      - name: kratos.config.selfservice.flows.settings.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/settings
      - name: ingress.public.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.admin.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      - name: ingress.admin.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.public.tls[0].hosts
        values:
          - {{ .Values.server_name }}

  - name: kratos-selfservice-ui-node
    chart: radar/kratos-selfservice-ui-node
    version: {{ .Values.kratos_ui._chart_version }}
    installed: {{ .Values.kratos_ui._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos_ui._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/kratos_ui/values.yaml"
      - {{ .Values.kratos_ui | toYaml | indent 8 | trim }}
    set:
      - name: serverName
        value: {{ .Values.server_name }}
      - name: ingress.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      - name: kratosPublicUrl
        value: https://{{ .Values.server_name }}/kratos
      - name: kratosBrowserUrl
        value: https://{{ .Values.server_name }}/kratos

  - name: hydra
    chart: ory/hydra
    version: {{ .Values.hydra._chart_version }}
    installed: {{ .Values.hydra._install }}
    timeout: {{ add .Values.base_timeout .Values.hydra._extra_timeout }}
    values:
      - "../etc/hydra/values.yaml"
      - {{ .Values.hydra | toYaml | indent 8 | trim }}

  - name: hydra-ui
    chart: ory/example-idp
    version: {{ .Values.hydra_ui._chart_version }}
    installed: {{ .Values.hydra_ui._install }}
    timeout: {{ add .Values.base_timeout .Values.hydra_ui._extra_timeout }}
    values:
      - "../etc/hydra-ui/values.yaml"
      - {{ .Values.hydra_ui | toYaml | indent 8 | trim }}