bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: postgresql
    chart: radar/postgresql
    version: {{ .Values.postgresql._chart_version }}
    installed: {{ .Values.postgresql._install }}
    timeout: {{ add .Values.base_timeout .Values.postgresql._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/postgresql/values.yaml"
      - {{ .Values.postgresql | toYaml | indent 8 | trim }}

  - name: management-portal
    chart: radar/management-portal
    version: {{ .Values.management_portal._chart_version }}
    installed: {{ .Values.management_portal._install }}
    timeout: {{ add .Values.base_timeout .Values.management_portal._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.management_portal | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: ingress_rate_limited.hosts
        values: [{{ .Values.server_name }}]
      - name: server_name
        value: {{ .Values.server_name }}
      - name: oauth_clients.radar_redcap_integrator.enable
        value: {{ .Values.radar_integration._install }}
      - name: oauth_clients.radar_upload_connect.enable
        value: {{ .Values.radar_upload_source_connector._install }}
      - name: oauth_clients.radar_upload_frontend.enable
        value: {{ .Values.radar_upload_connect_frontend._install }}
      - name: oauth_clients.radar_upload_backend.enable
        value: {{ .Values.radar_upload_connect_backend._install }}
      - name: oauth_clients.radar_rest_sources_authorizer.enable
        value: {{ .Values.radar_rest_sources_authorizer._install }}
      - name: oauth_clients.radar_rest_sources_auth_backend.enable
        value: {{ .Values.radar_rest_sources_backend._install }}
      - name: oauth_clients.radar_fitbit_connector.enable
        value: {{ .Values.radar_fitbit_connector._install }}
      - name: oauth_clients.radar_appconfig.enable
        value: {{ .Values.app_config._install }}
      - name: oauth_clients.appconfig_frontend.enable
        value: {{ .Values.app_config_frontend._install }}
      - name: oauth_clients.grafana_dashboard.enable
        value: {{ .Values.radar_grafana._install }}
      - name: oauth_clients.radar_push_endpoint.enable
        value: {{ .Values.radar_push_endpoint._install }}
      - name: oauth_clients.grafana_dashboard.redirect_uri
        values:
          - "https://dashboard.{{ .Values.server_name }}/login/generic_oauth"

  - name: app-config
    chart: radar/app-config
    version: {{ .Values.app_config._chart_version }}
    installed: {{ .Values.app_config._install }}
    timeout: {{ add .Values.base_timeout .Values.app_config._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.app_config | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: clientSecret
        value: {{ .Values.management_portal.oauth_clients.radar_appconfig.client_secret }}

  - name: app-config-frontend
    chart: radar/app-config-frontend
    version: {{ .Values.app_config_frontend._chart_version }}
    installed: {{ .Values.app_config_frontend._install }}
    timeout: {{ add .Values.base_timeout .Values.app_config_frontend._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.app_config_frontend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: authUrl
        value: https://{{ .Values.server_name }}/managementportal/oauth
      - name: authCallbackUrl
        value: https://{{ .Values.server_name }}/appconfig/login
