bases:
- ../environments.yaml

---

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

helmDefaults:
  timeout: 180
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: postgresql
    chart: radar/postgresql
    version: {{ .Values.postgresql._chart_version }}
    wait: false
    installed: {{ .Values.postgresql._install }}
    values:
      - "../etc/postgresql/values.yaml"
      - {{ .Values.postgresql | toYaml | indent 8 | trim }}
    set:
      - name: auth.postgresPassword
        value: {{ .Values.postgres_password }}
      - name: auth.replicationPassword
        value: {{ .Values.postgres_password }}

  - name: management-portal
    chart: radar/management-portal
    version: {{ .Values.management_portal._chart_version }}
    installed: {{ .Values.management_portal._install }}
    values:
      - {{ .Values.management_portal | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: server_name
        value: {{ .Values.server_name }}
      - name: oauth_clients.radar_redcap_integrator.enable
        value: {{ .Values.radar_integration._install }}
      - name: oauth_clients.radar_upload_connect.enable
        value: {{ .Values.radar_upload_source_connector._install }}
      - name: oauth_clients.radar_upload_frontend.enable
        value: {{ .Values.radar_upload_connect_frontend._install }}
      - name: oauth_clients.radar_upload_backend.enable
        value: {{ .Values.radar_upload_connect_backend._install }}
      - name: oauth_clients.radar_rest_sources_authorizer.enable
        value: {{ .Values.radar_rest_sources_authorizer._install }}
      - name: oauth_clients.radar_rest_sources_auth_backend.enable
        value: {{ .Values.radar_rest_sources_backend._install }}
      - name: oauth_clients.radar_fitbit_connector.enable
        value: {{ .Values.radar_fitbit_connector._install }}
      - name: oauth_clients.radar_appconfig.enable
        value: {{ .Values.app_config._install }}
      - name: oauth_clients.appconfig_frontend.enable
        value: {{ .Values.app_config_frontend._install }}
      - name: oauth_clients.grafana_dashboard.enable
        value: {{ .Values.radar_grafana._install }}
      - name: oauth_clients.radar_push_endpoint.enable
        value: {{ .Values.radar_push_endpoint._install }}
      - name: oauth_clients.grafana_dashboard.redirect_uri
        values:
          - "https://dashboard.{{ .Values.server_name }}/login/generic_oauth"

  - name: app-config
    chart: radar/app-config
    version: {{ .Values.app_config._chart_version }}
    installed: {{ .Values.app_config._install }}
    values:
      - {{ .Values.app_config | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: clientSecret
        value: {{ .Values.management_portal.oauth_clients.radar_appconfig.client_secret }}

  - name: app-config-frontend
    chart: radar/app-config-frontend
    version: {{ .Values.app_config_frontend._chart_version }}
    installed: {{ .Values.app_config_frontend._install }}
    values:
      - {{ .Values.app_config_frontend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
