bases:
- ../environments.yaml

---

releases:
  - name: kratos
    chart: ory/kratos
    version: {{ .Values.kratos._chart_version }}
    installed: {{ .Values.kratos._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos._extra_timeout }}
    values:
      - "../etc/kratos/values.yaml"
      - {{ .Values.kratos | toYaml | indent 8 | trim }}
    set:
      - name: serverName
        value: {{ .Values.server_name }}
      - name: kratos.config.dsn
        value: postgres://{{ .Values.management_portal.postgres.user }}:{{ .Values.management_portal.postgres.password }}@{{ .Values.management_portal.postgres.host }}:{{ .Values.management_portal.postgres.port }}/kratos
      - name: kratos.config.courier.smtp.connection_uri
        #  Note: encoding of "/" in password is necessary for the smtp connection_uri because kratos is not able to handle this.
        value: smtp://{{ .Values.management_portal.smtp.username }}:{{ replace "/" "%2F" .Values.management_portal.smtp.password }}@{{ .Values.management_portal.smtp.host }}:587
      - name: kratos.config.serve.public.base_url
        value: https://{{ .Values.server_name }}/kratos/
      - name: kratos.config.serve.admin.base_url
        value: https://{{ .Values.server_name }}/admin/kratos/
      - name: kratos.config.serve.public.cors.allowed_origins
        values:
          - https://{{ .Values.server_name }}/kratos-ui/
      - name: kratos.config.selfservice.default_browser_return_url
        value: https://{{ .Values.server_name }}/managementportal
      - name: kratos.config.selfservice.allowed_return_urls
        values:
          - https://{{ .Values.server_name }}/
        # FIXME: http://localhost/ is not a valid return URL for production
          - http://{{ .Values.server_name }}/
      - name: kratos.config.selfservice.flows.error.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/error
      - name: kratos.config.selfservice.flows.settings.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/settings
      - name: kratos.config.selfservice.flows.recovery.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/recovery
      - name: kratos.config.selfservice.flows.registration.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/registration
      - name: kratos.config.selfservice.flows.login.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/login
      - name: kratos.config.selfservice.flows.logout.after.default_browser_return_url
        value: https://{{ .Values.server_name }}/kratos-ui/login
      - name: kratos.config.selfservice.flows.verification.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/verification
      - name: kratos.config.selfservice.flows.verification.after.default_browser_return_url
        value: https://{{ .Values.server_name }}/kratos-ui
      - name: kratos.config.selfservice.flows.settings.ui_url
        value: https://{{ .Values.server_name }}/kratos-ui/settings
      {{- $values := .Values.kratos }}
      {{- $hasPublicIngress := and (hasKey $values "public") (hasKey $values.public "ingress") }}
      {{- $useTLSPublic := or (not $hasPublicIngress) (not (kindIs "invalid" $values.public.ingress.tls)) }}
      {{- if $useTLSPublic }}
      - name: ingress.public.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.admin.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      {{- end }}
      {{- $hasAdminIngress := and (hasKey $values "admin") (hasKey $values.admin "ingress") }}
      {{- $useTLSAdmin := or (not $hasAdminIngress) (not (kindIs "invalid" $values.admin.ingress.tls)) }}
      {{- if $useTLSAdmin }}
      - name: ingress.admin.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.public.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      {{- end }}

  - name: kratos-selfservice-ui-node
    chart: ory/kratos-selfservice-ui-node
    version: {{ .Values.kratos_ui._chart_version }}
    installed: {{ .Values.kratos_ui._install }}
    timeout: {{ add .Values.base_timeout .Values.kratos_ui._extra_timeout }}
    values:
      - "../etc/kratos_ui/values.yaml"
      - {{ .Values.kratos_ui | toYaml | indent 8 | trim }}
    set:
      - name: serverName
        value: {{ .Values.server_name }}
      {{- $values := .Values.kratos_ui }}
      {{- $useTLS := or (not (hasKey $values ".ingress")) (not (kindIs "invalid" .Values.ingress.tls)) }}
      {{- if $useTLS }}
      - name: ingress.hosts[0].host
        value: {{ .Values.server_name }}
      - name: ingress.tls[0].hosts
        values:
          - {{ .Values.server_name }}
      {{- end }}
      - name: kratosPublicUrl
        value: https://{{ .Values.server_name }}/kratos
      - name: kratosBrowserUrl
        value: https://{{ .Values.server_name }}/kratos
