bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-appserver-postgresql
    chart: radar/postgresql
    version: {{ .Values.radar_appserver_postgresql._chart_version }}
    installed: {{ .Values.radar_appserver_postgresql._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_appserver_postgresql._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/radar-appserver-postgresql/values.yaml"
      - {{ .Values.radar_appserver_postgresql | toYaml | indent 8 | trim }}

  - name: radar-appserver
    chart: radar/radar-appserver
    version: {{ .Values.radar_appserver._chart_version }}
    installed: {{ .Values.radar_appserver._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_appserver._extra_timeout }}
    {{ if .Values.radar_appserver_postgresql._install }}needs: [radar-appserver-postgresql]{{ end }}
    <<: *logFailedRelease    
    needs:
    - radar-appserver-postgresql
    values:
      - {{ .Values.radar_appserver | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
