bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-appserver-postgresql
    chart: radar/postgresql
    version: {{ .Values.radar_appserver_postgresql._chart_version }}
    installed: {{ .Values.radar_appserver_postgresql._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_appserver_postgresql._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/radar-appserver-postgresql/values.yaml"
      - {{ .Values.radar_appserver_postgresql | toYaml | indent 8 | trim }}

  - name: radar-appserver
    chart: radar/radar-appserver
    version: {{ .Values.radar_appserver._chart_version }}
    installed: {{ .Values.radar_appserver._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_appserver._extra_timeout }}
    <<: *logFailedRelease    
    needs:
    - radar-appserver-postgresql
    values:
      - {{ .Values.radar_appserver | toYaml | indent 8 | trim }}
      - extraEnvVars:
          - name: RADAR_FILE_UPLOAD_ENABLED
            value: "true"
          - name: RADAR_STORAGE_TYPE
            value: "s3"
          - name: RADAR_STORAGE_S3_URL
            value: "http://minio-headless:9000"
          - name: RADAR_STORAGE_S3_BUCKETNAME
            value: "radar-output-storage"
          - name: RADAR_STORAGE_S3_PATH_PREFIX
            value: "output"
          - name: RADAR_STORAGE_S3_PATH_COLLECTPERDAY
            value: "true"
          - name: SPRING_SERVLET_MULTIPART_MAXFILESIZE
            value: "20MB"
          - name: SPRING_SERVLET_MULTIPART_ENABLED
            value: "true"
          - name: RADAR_STORAGE_S3_ACCESSKEY
            value: {{ .Values.s3_access_key }}
          - name: RADAR_STORAGE_S3_SECRETKEY
            value: {{ .Values.s3_secret_key }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
