bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: radar-fitbit-connector
    chart: ../charts/radar-fitbit-connector
    installed: {{ .Values.radar_fitbit_connector._install }}
    values:
      - {{ .Values.radar_fitbit_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: fitbit_api_client
        value: {{ .Values.fitbit_api_client }}
      - name: fitbit_api_secret
        value: {{ .Values.fitbit_api_secret }}
      - name: oauthClientSecret
        value: {{ .Values.management_portal.oauth_clients.radar_fitbit_connector.client_secret }}

  - name: radar-rest-sources-authorizer
    chart: ../charts/radar-rest-sources-authorizer
    installed: {{ .Values.radar_rest_sources_authorizer._install }}
    values:
      - {{ .Values.radar_rest_sources_authorizer | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}

  - name: radar-rest-sources-backend
    chart: ../charts/radar-rest-sources-backend
    installed: {{ .Values.radar_rest_sources_backend._install }}
    values:
      - {{ .Values.radar_rest_sources_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: restSourceClients[0].clientId
        value: {{ .Values.fitbit_api_client }}
      - name: restSourceClients[0].clientSecret
        value: {{ .Values.fitbit_api_secret }}
      - name: client_secret
        value: {{ .Values.management_portal.oauth_clients.radar_rest_sources_auth_backend.client_secret }}
