environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: true
  timeout: 600

releases:
  - name: radar-fitbit-connector
    chart: ../charts/radar-fitbit-connector
    installed: {{ .Values.radar_fitbit_connector._install }}
    values:
      - {{ .Values.radar_fitbit_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: fitbit_api_client
        value: {{ .Values.fitbit_api_client }}
      - name: fitbit_api_secret
        value: {{ .Values.fitbit_api_secret }}

  - name: radar-rest-sources-authorizer
    chart: ../charts/radar-rest-sources-authorizer
    installed: {{ .Values.radar_rest_sources_authorizer._install }}
    values:
      - {{ .Values.radar_rest_sources_authorizer | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]

  - name: radar-rest-sources-backend
    chart: ../charts/radar-rest-sources-backend
    installed: {{ .Values.radar_rest_sources_backend._install }}
    values:
      - {{ .Values.radar_rest_sources_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: postgres.password
        value: {{ .Values.postgres_password }}
      - name: fitbit_api_client
        value: {{ .Values.fitbit_api_client }}
      - name: fitbit_api_secret
        value: {{ .Values.fitbit_api_secret }}
      - name: client_secret
        value: {{ .Values.management_portal.client_secrets.radar_rest_sources_backend }}