bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: radar-fitbit-connector
    chart: radar/radar-fitbit-connector
    version: {{ .Values.radar_fitbit_connector._chart_version }}
    installed: {{ .Values.radar_fitbit_connector._install }}
    values:
      - {{ .Values.radar_fitbit_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      {{- if hasKey .Values "fitbit_api_client" }}
      - name: fitbit_api_client
        value: {{ .Values.fitbit_api_client }}
      {{- end }}
      {{- if hasKey .Values "fitbit_api_secret" }}
      - name: fitbit_api_secret
        value: {{ .Values.fitbit_api_secret }}
      {{- end }}
      - name: oauthClientSecret
        value: {{ dig "radar_fitbit_connector" "client_secret" "" .Values.management_portal.oauth_clients }}

  - name: radar-rest-sources-authorizer
    chart: radar/radar-rest-sources-authorizer
    version: {{ .Values.radar_rest_sources_authorizer._chart_version }}
    installed: {{ .Values.radar_rest_sources_authorizer._install }}
    values:
      - {{ .Values.radar_rest_sources_authorizer | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}

  - name: radar-rest-sources-backend
    chart: radar/radar-rest-sources-backend
    version: {{ .Values.radar_rest_sources_backend._chart_version }}
    installed: {{ .Values.radar_rest_sources_backend._install }}
    values:
      - {{ .Values.radar_rest_sources_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
      {{- if hasKey .Values "fitbit_api_client" }}
      - name: restSourceClients.fitbit.clientId
        value: {{ .Values.fitbit_api_client }}
      {{- end }}
      {{- if hasKey .Values "fitbit_api_secret" }}
      - name: restSourceClients.fitbit.clientSecret
        value: {{ .Values.fitbit_api_secret }}
      {{- end }}
      - name: restSourceClients.fitbit.enable
        value: {{ .Values.radar_fitbit_connector._install }}
      - name: restSourceClients.garmin.enable
        value: {{ and .Values.radar_push_endpoint._install .Values.radar_push_endpoint.garmin.enabled }}
      - name: restSourceClients.garmin.clientId
        value: {{ dig "restSourceClients" "garmin" "clientId" (dig "garmin" "consumerKey" "" .Values.radar_push_endpoint) .Values.radar_rest_sources_backend }}
      - name: restSourceClients.garmin.clientSecret
        value: {{ dig "restSourceClients" "garmin" "clientSecret" (dig "garmin" "consumerSecret" "" .Values.radar_push_endpoint) .Values.radar_rest_sources_backend }}
      - name: client_secret
        value: {{ dig "client_secret" (dig "oauth_clients" "radar_rest_sources_auth_backend" "client_secret" "" .Values.management_portal) .Values.radar_rest_sources_backend }}
