bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: radar-fitbit-connector
    chart: radar/radar-fitbit-connector
    version: 0.1.2
    installed: {{ .Values.radar_fitbit_connector._install }}
    values:
      - {{ .Values.radar_fitbit_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: fitbit_api_client
        value: {{ .Values.fitbit_api_client }}
      - name: fitbit_api_secret
        value: {{ .Values.fitbit_api_secret }}
      - name: oauthClientSecret
        value: {{ if hasKey .Values.management_portal.oauth_clients "radar_fitbit_connector" -}}{{ .Values.management_portal.oauth_clients.radar_fitbit_connector.client_secret }}{{- end }}

  - name: radar-rest-sources-authorizer
    chart: radar/radar-rest-sources-authorizer
    version: 0.2.2
    installed: {{ .Values.radar_rest_sources_authorizer._install }}
    values:
      - {{ .Values.radar_rest_sources_authorizer | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}

  - name: radar-rest-sources-backend
    chart: radar/radar-rest-sources-backend
    version: 0.2.3
    installed: {{ .Values.radar_rest_sources_backend._install }}
    values:
      - {{ .Values.radar_rest_sources_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
      {{- if hasKey .Values "fitbit_api_client" }}
      - name: restSourceClients.fitbit.clientId
        value: {{ .Values.fitbit_api_client }}
      {{- end }}
      {{- if hasKey .Values "fitbit_api_secret" }}
      - name: restSourceClients.fitbit.clientSecret
        value: {{ .Values.fitbit_api_secret }}
      {{- end }}
      - name: restSourceClients.fitbit.enable
        value: {{ .Values.radar_fitbit_connector._install }}
      - name: restSourceClients.garmin.enable
        value: {{ .Values.radar_push_endpoint.garmin.enabled }}
      {{- if hasKey .Values "radar_push_endpoint.garmin.consumerKey" }}
      - name: restSourceClients.garmin.clientId
        value: {{ .Values.radar_push_endpoint.garmin.consumerKey }}
      {{- end }}
      {{- if hasKey .Values "radar_push_endpoint.garmin.consumerSecret" }}
      - name: restSourceClients.garmin.clientSecret
        value: {{ .Values.radar_push_endpoint.garmin.consumerSecret }}
      {{- end }}
      {{ if hasKey .Values.management_portal.oauth_clients "radar_rest_sources_auth_backend" }}
      - name: client_secret
        value: {{ .Values.management_portal.oauth_clients.radar_rest_sources_auth_backend.client_secret }}
      {{ end }}
