bases:
- ../environments.yaml

---

helmDefaults:
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: timescaledb
    chart: radar/postgresql
    version: {{ .Values.timescaledb._chart_version }}
    installed: {{ .Values.timescaledb._install }}
    values:
      - "../etc/timescaledb/values.yaml"
      - {{ .Values.timescaledb | toYaml | indent 8 | trim }}
    set:
      {{- if eq .Values.grafana_metrics_username "postgres" }}
      - name: global.postgresql.auth.postgresPassword
        value: {{ .Values.timescaledb_password }}
      {{- else }}
      - name: global.postgresql.auth.username
        value: {{ .Values.grafana_metrics_username }}
      - name: global.postgresql.auth.password
        value: {{ .Values.timescaledb_password }}
      {{- end }}
      - name: auth.database
        value: {{ .Values.timescaledb_db_name }}

  - name: radar-grafana
    chart: radar/grafana
    version: {{ .Values.radar_grafana._chart_version }}
    installed: {{ .Values.radar_grafana._install }}
    values:
      - "../etc/radar-grafana/values.yaml"
      - {{ .Values.radar_grafana | toYaml | indent 8 | trim }}
    set:
      - name: adminPassword
        value: {{ .Values.grafana_password }}
      - name: env.POSTGRES_DB
        value: {{ .Values.timescaledb_db_name | quote }}
      - name: envRenderSecret.POSTGRES_PASSWORD
        value: {{ .Values.timescaledb_password }}
      - name: ingress.hosts
        values: ["dashboard.{{ .Values.server_name }}"]
      - name: "grafana\\.ini.server.root_url"
        value: "https://dashboard.{{ .Values.server_name }}/"
      - name: ingress.tls[0].secretName
        value: radar-base-tls-dashboard
      - name: ingress.tls[0].hosts
        values: ["dashboard.{{ .Values.server_name }}"]
      - name: "grafana\\.ini.metrics.basic_auth_username"
        value: {{ .Values.grafana_metrics_username }}
      - name: "grafana\\.ini.metrics.basic_auth_password"
        value: {{ .Values.grafana_metrics_password }}
      - name: "grafana\\.ini.auth\\.generic_oauth.auth_url"
        value: "https://{{ .Values.server_name }}/managementportal/oauth/authorize"
      - name: "grafana\\.ini.auth\\.generic_oauth.token_url"
        value: "https://{{ .Values.server_name }}/managementportal/oauth/token"

  - name: radar-jdbc-connector
    chart: radar/radar-jdbc-connector
    version: {{ .Values.radar_jdbc_connector._chart_version }}
    installed: {{ .Values.radar_jdbc_connector._install }}
    values:
      - {{ .Values.radar_jdbc_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: jdbc.password
        value: {{ .Values.timescaledb_password }}
      - name: jdbc.username
        value: {{ .Values.grafana_metrics_username }}
      - name: jdbc.url
        value: {{ dig "jdbc" "url" (printf "jdbc:postgresql://timescaledb-postgresql-hl:5432/%s" .Values.timescaledb_db_name) .Values.radar_jdbc_connector }}
