bases:
- ../environments.yaml

---

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: timescaledb
    chart: stable/postgresql
    installed: {{ .Values.timescaledb._install }}
    values:
      - "../charts/timescaledb/values.yaml"
      - {{ .Values.timescaledb | toYaml | indent 8 | trim }}
    set:
      - name: postgresqlPassword
        value: {{ .Values.timescaledb_password }}
      - name: postgresqlUsername
        value: {{ .Values.timescaledb_username }}
      - name: postgresqlDatabase
        value: {{ .Values.timescaledb_db_name }}

  - name: radar-grafana
    chart: stable/grafana
    installed: {{ .Values.radar_grafana._install }}
    values:
      - "../charts/radar-grafana/values.yaml"
      - {{ .Values.radar_grafana | toYaml | indent 8 | trim }}
    set:
      - name: adminPassword
        value: {{ .Values.grafana_password }}
      - name: env.POSTGRES_DB
        value: {{ .Values.timescaledb_db_name | quote }}
      - name: env.POSTGRES_PASSWORD
        value: {{ .Values.timescaledb_password }}
      - name: ingress.hosts
        values: ["dashboard.{{ .Values.server_name }}"]
      - name: ingress.tls[0].secretName
        value: radar-base-tls-dashboard
      - name: ingress.tls[0].hosts
        values: ["dashboard.{{ .Values.server_name }}"]

  - name: radar-jdbc-connector
    chart: ../charts/radar-jdbc-connector
    installed: {{ .Values.radar_jdbc_connector._install }}
    values:
      - "../charts/radar-jdbc-connector/values.yaml"
      - {{ .Values.radar_jdbc_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: timescaledb.password
        value: {{ .Values.timescaledb_password }}
      - name: timescaledb.username
        value: {{ .Values.timescaledb_username }}
      - name: timescaledb.database_name
        value: {{ .Values.timescaledb_db_name }}
