bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  force: true
  timeout: 120
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: hdfs
    chart: ../kubernetes-HDFS/charts/hdfs-k8s
    installed: {{ .Values.hdfs._install }}
    values:
      - {{ .Values.hdfs | toYaml | indent 8 | trim }}

  - name: radar-connect-hdfs-sink
    chart: ../charts/radar-connect-hdfs-sink
    installed: {{ .Values.radar_connect_hdfs_sink._install }}
    values:
      - {{ .Values.radar_connect_hdfs_sink | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}

  - name: radar-output
    chart: ../charts/radar-output
    wait: true
    installed: {{ .Values.radar_output._install }}
    values:
      - {{ .Values.radar_output | toYaml | indent 8 | trim }}
