bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-gateway
    chart: radar/radar-gateway
    version: {{ .Values.radar_gateway._chart_version }}
    installed: {{ .Values.radar_gateway._install }}
    <<: *logFailedRelease    
    values:
      - {{ .Values.radar_gateway | toYaml | indent 8 | trim }}
      - {{ .Values.confluent_cloud | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: cc.enabled
        value: {{ .Values.confluent_cloud.enabled }}
      - name: serviceMonitor.enabled
        value: {{ .Values.kube_prometheus_stack._install }}
      {{- if .Values.confluent_cloud.enabled }}
      - name: schemaRegistry
        value: {{ .Values.confluent_cloud.cc.schemaRegistryUrl }}
      - name: bootstrapServers
        value: {{ .Values.confluent_cloud.cc.bootstrapServerurl }}
      {{ end }}
