helmDefaults:
  atomic: true
  timeout: 600

releases:
  - name: cp-kafka-rest
    chart: ../cp-helm-charts/charts/cp-kafka-rest
    wait: false
    installed: {{ requiredEnv "RADAR_INSTALL_INGESTION" }}
    values:
      - "../charts/cp-kafka-rest/values.yaml"
    set:
      - name: imageTag
        value: "{{ requiredEnv "CP_KAFKA_REST_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "CP_KAFKA_REST_REPLICA_COUNT" }}"
  - name: radar-gateway
    chart: ../charts/radar-gateway
    installed: {{ requiredEnv "RADAR_INSTALL_INGESTION" }}
    set:
      - name: image.tag
        value: "{{ requiredEnv "RADAR_GATEWAY_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "RADAR_GATEWAY_REPLICA_COUNT" }}"
      - name: ingress.hosts
        values: ["{{ requiredEnv "SERVER_NAME" }}"]
