bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-backend-monitor
    chart: radar/radar-backend
    version: {{ .Values.radar_backend_monitor._chart_version }}
    installed: {{ .Values.radar_backend_monitor._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_backend_monitor._extra_timeout }}
    {{ if .Values.cp_kafka._install }}
    needs:
      - cp-zookeeper
      - cp-kafka
      - cp-schema-registry
      # Does this still exist?
      # - cp-kafka-rest
    {{ end }}
    <<: *logFailedRelease
    values:
      - "../etc/radar-backend-monitor/values.yaml"
      - {{ .Values.radar_backend_monitor | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}

  - name: radar-backend-stream
    chart: radar/radar-backend
    version: {{ .Values.radar_backend_monitor._chart_version }}
    installed: {{ .Values.radar_backend_stream._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_backend_stream._extra_timeout }}
    {{ if .Values.cp_kafka._install }}
    needs:
      - cp-zookeeper
      - cp-kafka
      - cp-schema-registry
      # Does this still exist?
      # - cp-kafka-rest
    {{ end }}
    <<: *logFailedRelease    
    values:
      - "../etc/radar-backend-stream/values.yaml"
      - {{ .Values.radar_backend_stream | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
