bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-integration
    chart: radar/radar-integration
    version: {{ .Values.radar_integration._chart_version }}
    installed: {{ .Values.radar_integration._install }}
    timeout: {{ dig "_timeout" .Values.timeout .Values.radar_integration }}
    <<: *logFailedRelease    
    values:
      - {{ .Values.radar_integration | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: oauth_client_secret
        value: {{ dig "oauth_client_secret" (dig "oauth_clients" "radar_redcap_integrator" "client_secret" "" .Values.management_portal) .Values.radar_integration }}
