bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: radar-integration
    chart: ../charts/radar-integration
    installed: {{ .Values.radar_integration._install }}
    values:
      - {{ .Values.radar_integration | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: oauth_client_secret
        value: {{- if hasKey .Values.management_portal.oauth_clients "radar_redcap_integrator" -}}{{ .Values.management_portal.oauth_clients.radar_redcap_integrator.client_secret }}{{- end }}
