bases:
- ../environments.yaml

---

{{ readFile "../etc/helmfile-templates.yaml" }}

releases:
  - name: radar-upload-postgresql
    chart: radar/postgresql
    version: {{ .Values.radar_upload_postgresql._chart_version }}
    installed: {{ .Values.radar_upload_postgresql._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_upload_postgresql._extra_timeout }}
    <<: *logFailedRelease
    values:
      - "../etc/radar-upload-postgresql/values.yaml"
      - {{ .Values.radar_upload_postgresql | toYaml | indent 8 | trim }}
    set:
      - name: global.postgresql.auth.postgresPassword
        value: {{ .Values.radar_upload_postgres_password }}
      - name: auth.replicationPassword
        value: {{ .Values.radar_upload_postgres_password }}

  - name: radar-upload-connect-backend
    chart: radar/radar-upload-connect-backend
    version: {{ .Values.radar_upload_connect_backend._chart_version }}
    installed: {{ .Values.radar_upload_connect_backend._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_upload_connect_backend._extra_timeout }}
    {{ if .Values.radar_upload_postgresql._install }}needs: [radar-upload-postgresql]{{ end }}
    <<: *logFailedRelease
    values:
      - {{ .Values.radar_upload_connect_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
      - name: postgres.password
        value: {{ .Values.radar_upload_postgres_password }}
      - name: client_secret
        value: {{ dig "client_secret" (dig "oauth_clients" "radar_upload_backend" "client_secret" "" .Values.management_portal) .Values.radar_upload_connect_backend }}

  - name: radar-upload-connect-frontend
    chart: radar/radar-upload-connect-frontend
    version: {{ .Values.radar_upload_connect_frontend._chart_version }}
    installed: {{ .Values.radar_upload_connect_frontend._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_upload_connect_frontend._extra_timeout }}
    <<: *logFailedRelease
    values:
      - {{ .Values.radar_upload_connect_frontend | toYaml | indent 8 | trim }}
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]

  - name: radar-upload-source-connector
    chart: radar/radar-upload-source-connector
    version: {{ .Values.radar_upload_source_connector._chart_version }}
    installed: {{ .Values.radar_upload_source_connector._install }}
    timeout: {{ add .Values.base_timeout .Values.radar_upload_source_connector._extra_timeout }}
    <<: *logFailedRelease    
    values:
      - {{ .Values.radar_upload_source_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: bucketAccessKey
        value: {{ .Values.s3_access_key }}
      - name: bucketSecretKey
        value: {{ .Values.s3_secret_key }}
      - name: client_secret
        value: {{ dig "client_secret" (dig "oauth_clients" "radar_upload_connect" "client_secret" "" .Values.management_portal) .Values.radar_upload_source_connector }}
