bases:
- ../environments.yaml

---

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

helmDefaults:
  atomic: true
  timeout: 600
  kubeContext: {{ .Values.kubeContext }}

releases:
  - name: radar-upload-postgresql
    chart: bitnami/postgresql
    version: 9.6.0
    wait: false
    installed: {{ .Values.radar_upload_postgresql._install }}
    values:
      - "../etc/radar-upload-postgresql/values.yaml"
      - {{ .Values.radar_upload_postgresql | toYaml | indent 8 | trim }}
    set:
      - name: postgresqlPassword
        value: {{ .Values.radar_upload_postgres_password }}
      - name: replication.password
        value: {{ .Values.radar_upload_postgres_password }}

  - name: radar-upload-connect-backend
    chart: ../charts/radar-upload-connect-backend
    installed: {{ .Values.radar_upload_connect_backend._install }}
    values:
      - {{ .Values.radar_upload_connect_backend | toYaml | indent 8 | trim }}
    set:
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]
      - name: serverName
        value: {{ .Values.server_name }}
      - name: postgres.password
        value: {{ .Values.radar_upload_postgres_password }}
      - name: client_secret
        value: {{ .Values.management_portal.oauth_clients.radar_upload_backend.client_secret }}

  - name: radar-upload-connect-frontend
    chart: ../charts/radar-upload-connect-frontend
    installed: {{ .Values.radar_upload_connect_frontend._install }}
    values:
      - {{ .Values.radar_upload_connect_frontend | toYaml | indent 8 | trim }}
    set:
      - name: server_name
        value: {{ .Values.server_name }}
      - name: ingress.hosts
        values: [{{ .Values.server_name }}]

  - name: radar-upload-source-connector
    chart: ../charts/radar-upload-source-connector
    installed: {{ .Values.radar_upload_source_connector._install }}
    values:
      - {{ .Values.radar_upload_source_connector | toYaml | indent 8 | trim }}
    set:
      - name: kafka_num_brokers
        value: {{ .Values.kafka_num_brokers }}
      - name: s3Endpoint
        value: {{ .Values.minio.s3Endpoint }}
      - name: bucketAccessKey
        value: {{ .Values.minio.accessKey }}
      - name: bucketSecretKey
        value: {{ .Values.minio.secretKey }}
      - name: client_secret
        value: {{ .Values.management_portal.oauth_clients.radar_upload_connect.client_secret }}
