environments:
  default:
    values:
    - ../base.yaml
    - ../production.yaml

helmDefaults:
  atomic: true
  force: true
  timeout: 600

releases:
  - name: velero
    chart: ../charts/velero
    namespace: velero
    version: 2.12.0
    installed: {{ .Values.velero._install }}
    values:
      - "../charts/velero/values.yaml"
      - {{ .Values.velero | toYaml | indent 8 | trim }}
