bases:
- ../environments.yaml

---

helmDefaults:
  atomic: true
  timeout: 120
  kubeContext: {{ .Values.kubeContext }}

repositories:
  - name: radar
    url: https://radar-base.github.io/radar-helm-charts

releases:
  - name: velero
    chart: radar/velero-s3-deployment
    namespace: velero
    version: {{ .Values.velero._chart_version }}
    installed: {{ .Values.velero._install }}
    values:
      - {{ .Values.velero | toYaml | indent 8 | trim }}
    set:
      - name: local.accessKey
        value: {{ dig "local" "accessKey" .Values.s3_access_key .Values.velero }}
      - name: local.secretKey
        value: {{ dig "local" "secretKey" .Values.s3_secret_key .Values.velero }}
