name: Check chart compatibility with Kubernetes

on:
  workflow_dispatch: {}
  schedule:
    # Weekly: Monday at 5:30
    - cron: '0 6 * * 1'

env:
  K8S_TARGET_VERSION: "v1.25.0"

jobs:
  check-compatibility:
    strategy:
      matrix:
        kubeVersion: ["v1.23.0", "v1.24.0", "v1.25.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          install-helm-plugins: yes
          install-kubectl: yes

      - name: Set up helmfile config
        run: cp .github/environments.yaml environments.yaml

      - uses: cpanato/kubepug-installer@v1.0.0

      - name: Check updates
        run: helmfile template | kubepug --error-on-deprecated --error-on-deleted --input-file /dev/stdin' --k8s-version ${{ matrix.kubeVersion }}
