name: Check chart updates

on:
  workflow_dispatch: {}
  schedule:
    # Weekly: Monday at 5:30
    - cron: '30 5 * * 1'

jobs:
  chart-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup-helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          install-helm-plugins: no
          install-kubectl: no

      - name: Set up helmfile config
        run: cp .github/environments.yaml environments.yaml

      - name: Check updates
        run: bin/chart-updates
