apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "s3-proxy.fullname" . }}
  labels:
    app: {{ template "s3-proxy.name" . }}
    chart: {{ template "s3-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
