apiVersion: v1
kind: Secret
metadata:
  name: {{ template "s3-proxy.fullname" . }}
  labels:
    app: {{ template "s3-proxy.name" . }}
    chart: {{ template "s3-proxy.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  s3Credential: {{ .Values.s3.credential | b64enc | quote }}
  targetCredential: {{ .Values.target.credential | b64enc | quote }}
